---

env:
  browser: true
  es6: true
  node: true
  jest: true

extends:
  - 'plugin:react/recommended'
  - airbnb

settings:
  import/resolver:
    - node
    - webpack

rules:
  import/extensions: 0
  react/prop-types: 0
  no-console: 0

parser: babel-eslint